# ─── Stage 1: Build ──────────────────────────────────────────────────────────
# Use the LTS slim image to keep the build environment lean.
# We pin to a minor version so Cloud Build is reproducible.
FROM node:22-slim AS builder

WORKDIR /app

# Install OpenSSL — required by Prisma's query engine binary at generate time.
RUN apt-get update -y && apt-get install -y --no-install-recommends openssl && rm -rf /var/lib/apt/lists/*

# Copy manifests first to benefit from Docker layer caching.
COPY package.json package-lock.json ./
COPY prisma ./prisma

# Install ALL dependencies (including devDeps such as typescript and ts-node)
# so the build stage can compile TypeScript and generate Prisma Client.
# The postinstall hook runs `prisma generate && npm run build` automatically.
RUN npm ci

# Copy the rest of the source.
COPY . .

# Compile TypeScript → dist/ (tsc reads tsconfig.json; output goes to ./dist).
# Prisma Client was already generated by the postinstall hook above.
RUN npm run build


# ─── Stage 2: Runtime ────────────────────────────────────────────────────────
# Fresh image — devDependencies are NOT copied from the builder.
FROM node:22-slim AS runtime

WORKDIR /app

# OpenSSL is required by the Prisma query engine at *runtime*.
RUN apt-get update -y && apt-get install -y --no-install-recommends openssl && rm -rf /var/lib/apt/lists/*

# Copy manifests to install only production dependencies.
COPY package.json package-lock.json ./
COPY prisma ./prisma

# --ignore-scripts prevents postinstall from re-running the full build.
# We still need `prisma generate` to embed the Prisma Client for runtime.
RUN npm ci --omit=dev --ignore-scripts && npx prisma generate

# Copy compiled JavaScript from the build stage.
COPY --from=builder /app/dist ./dist

# Cloud Run injects PORT at startup. Express reads `process.env.PORT || 5000`.
# We expose 8080 as Cloud Run's default container port; the app binds
# to whatever PORT Cloud Run provides (always 8080 in managed Cloud Run).
EXPOSE 8080

# Never run as root in a container.
USER node

CMD ["node", "dist/index.js"]
